server:
    port: 80



eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name : api-gateway
    cloud:
        gateway:
            routes:
                - id: spring-customer-service
                  uri: lb://spring-customer-service
                  predicates:
                    - Path=/api/customers/**
                  filters:
                    - AuthFilter
                - id: spring-product-service
                  uri: lb://spring-product-service
                  predicates:
                    - Path=/api/products/**
                  filters:
                    - AuthFilter
                - id: order-service
                  uri: lb://order-service
                  predicates:
                    - Path=/api/orders/**
                  filters:
                    - AuthFilter
                - id: auth_service
                  uri: lb://auth-service
                  predicates:
                    - Path=/api/auth/**

management:
    tracing:
        sampling:
            probability: 1.0


