server:
    port: 8083

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dborder
        username: root
        password: 121212
        driver-class-name: com.mysql.jdbc.Driver
        hikari: 
            minimumIdle: 2
            maximumPoolSize: 5
            cachePrepStmts: true
            prepStmtChaceSize: 250
            prepStmtCacheSqlLimit: 2048
            userServerPrepStmts: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
    health:
        circuitbreakers:
            enabled: true
        

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10