server:
    port: 8081

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        version: Customer Service v1.3 
    datasource:
        url: jdbc:mysql://localhost:3306/dbcustomer
        username: root
        password: 121212
        driver-class-name: com.mysql.jdbc.Driver
        hikari: 
            minimumIdle: 2
            maximumPoolSize: 5
            cachePrepStmts: true
            prepStmtChaceSize: 250
            prepStmtCacheSqlLimit: 2048
            userServerPrepStmts: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
management:
    endpoints:
        web:
            exposure:
                include: "*"